"""Automatic migration based on schema update

Revision ID: ec955e621c18
Revises: f7f058e9e9e4
Create Date: 2024-09-08 15:57:27.830414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec955e621c18'
down_revision: Union[str, None] = 'f7f058e9e9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
