"""Automatic migration based on schema update

Revision ID: f7f058e9e9e4
Revises: e41a4b5538c1
Create Date: 2024-09-08 15:50:03.915813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f058e9e9e4'
down_revision: Union[str, None] = 'e41a4b5538c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
